version: '3.7'
services:

  front-envoy:
    build:
      context: ../apps
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      # Expose ports 80 (for general traffic) and 8001 (for the admin server)
      - "8000"
      - "8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  service_blue:
    build:
      context: ../apps
      dockerfile: Dockerfile-service
    volumes:
      - ./service-blue-envoy-zipkin.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_blue
    environment:
      - SERVICE_NAME=blue
    expose:
      - "80"
  service_green:
    build:
      context: ../apps
      dockerfile: Dockerfile-service
    volumes:
      - ./service-green-envoy-zipkin.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_green
    environment:
      - SERVICE_NAME=green
    expose:
      - "80"
  service_red:
    build:
      context: ../apps
      dockerfile: Dockerfile-service
    volumes:
      - ./service-red-envoy-zipkin.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service_red
    environment:
      - SERVICE_NAME=red
    expose:
      - "80"
  zipkin:
    image: openzipkin/zipkin
    networks:
      envoymesh:
        aliases:
          - zipkin
    expose:
      - "9411"
    ports:
      - "9411:9411"

networks:
  envoymesh: {}
